---
title: "stat135_hw2_code"
author: "Vinay Maruri"
date: "7/5/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###QUESTION 7 CODE


```{r}
#session view hours input for question 7.
B_view_hours <- c(1.17, 1.417, 0.419, 1.426, 1.203, 0.136, 0.57,
0.844, 0.78, 1.014, 0.75, 0.075, 0.318, 0.584, 1.632, 1.738,
0.624, 0.609, 0.72, 1.504, 1.583, 0.429, 0.866, 1.214, 0.947,
1.546, 1.148, 0.345, 1.384, 0.884, 1.648, 0.151, 0.143, 1.203,
0.699, 1.516, 2.254, 0.297, 0.767, 1.147, 0.569, 3.088, 0.617,
1.575, 1.211, 0.917, 0.025, 0.979, 0.277, 2.751, 3.859, 1.314,
1.073, 0.424, 0.119, 0.726, 0.322, 0.854, 0.844, 0.238, 0.991,
1.366, 1.349, 0.387, 0.957, 0.398, 0.993, 0.678, 0.431, 0.8,
0.719, 0.173, 0.399, 0.201, 2.276, 0.702, 1.911, 0.481, 0.541,
1.051, 0.82, 1.285, 0.322, 2.134, 0.775, 1.565, 2.399, 0.576,
0.262, 0.612, 0.932, 0.747, 0.936, 1.748, 0.81, 1.225, 1.277,
1.386, 0.431, 0.508, 0.146, 0.591, 0.97, 1.104, 0.418, 1.501,
0.702, 0.108, 0.51, 2.014, 0.426, 0.87, 1.36, 0.864, 0.412,
0.802, 0.215, 0.243, 0.658, 0.671, 1.31, 0.13, 0.223, 1.294,
1.601, 0.966, 0.415, 0.529, 0.481, 0.416, 1.347, 1.345, 0.192,
1.213, 0.938, 0.317, 0.341, 0.78, 1.945, 1.004, 1.407, 0.579,
0.621, 0.842, 0.307, 0.227, 0.842, 0.836, 1.386, 0.841, 1.201,
0.438, 1.425, 2.186, 0.327, 0.197, 0.436, 0.606, 1.797, 0.809,
0.587, 2.253, 1.294, 0.885, 0.82, 1.235, 0.31, 2.275, 1.521,
0.719, 2.741, 0.256, 0.614, 0.747, 1.367, 1.333, 2.02, 0.769,
1.636, 0.864, 0.131, 0.648, 0.846, 0.304, 0.751, 1.814, 0.838,
0.82, 0.935, 0.58, 0.907, 0.832, 1.161, 0.517, 0.775, 1.482,
0.458, 1.449, 3.422, 2.058)
```

```{r}
#specifying our log-likelihood function.
ll_function <- function(a, b, df){
  n = length(df)
  log_likelihood_fn <- n*a*log(b) - n*log(gamma(a)) + (a - 1)*sum(log(df)) - b*sum(df)
  return(log_likelihood_fn)
}
ll_function(2, 2, B_view_hours)
```

```{r}
#we expect alpha and beta hat mle to be in range 1-3, so set up a grid search over that area
alpha <- seq(1, 3, length.out = 200)
beta <- seq(1, 3, length.out = 200)

#then actually execute the grid search.

ll_values <- matrix(NA, 200, 200)
for(x in 1:200){
  for(y in 1:200){
    ll_values[x, y] <- ll_function(alpha[x], beta[y], B_view_hours)
  }
}
```

```{r}
#find the maximum likelihood and associated alpha/beta params
max(ll_values)
max_matrix <- which(ll_values == max(ll_values), arr.ind = TRUE)
max_matrix
```
```{r}
#hence, alpha[118] is alpha_mle, beta[129] is beta_mle
alpha[118]
beta[129]
```

```{r}
#compute fisher information matrix (as defined by lecture 5, slide 7 since Design B has population distribution gamma(alpha, beta) from Question 6 of this homework.)
fisher_matrix = matrix(NA, ncol = 2, nrow = 2)
fisher_matrix[1, 1] <- trigamma(alpha[118])
fisher_matrix[1, 2] <- -1/beta[129]
fisher_matrix[2, 1] <- -1/beta[129]
fisher_matrix[2, 2] <- alpha[118]/(beta[129]*beta[129])
```

```{r}
#compute confidence intervals (first for alpha, then for beta)
alpha_ci <- c(alpha[118] - (1.96/(sqrt(200 * (fisher_matrix[1,1] - 1/alpha[118])))), alpha[118] + (1.96/(sqrt(200 * (fisher_matrix[1,1] - 1/alpha[118])))))
beta_ci <- c(beta[129] - ((1.96*sqrt(beta[129]^2 * fisher_matrix[1,1]))/(sqrt(200 * (alpha[118]*fisher_matrix[1,1] - 1)))), beta[129] + ((1.96*sqrt(beta[129]^2 * fisher_matrix[1,1]))/(sqrt(200 * (alpha[118]*fisher_matrix[1,1] - 1)))))
alpha_ci
beta_ci
```

###Question 8 CODE

```{r}
#(1): generating 150 iid observations from N(2,4) population and plotting in a histogram
#use rnorm function to generate observations (mean = 2, variance = 4, sd = 2)
set.seed(99)
observations <- rnorm(n=150, mean=2, sd=2)
hist(x=observations)
```
```{r}
#(2): calculate mm estimate for mu and sigma [as seen in question, this is equal to the sample mean and sample standard deviation]
mean(observations)
var(observations)
sd(observations)
observations
```

```{r}
#(3) (b) start from N(1.793418, 3.624037), generate 500 samples each of size 100
simulations <- replicate(n=500, rnorm(n=100, mean = 1.793418, sd = 1.90369))
#[each column represents a sample of size 100, 500 columns in total.]
simulations
```

```{r}
#sample mean is mm estimate of mu
sample_means <- colMeans(simulations)
#sample sd is the mm estimate of sigma [generated using the apply() function using the base r variance function over the columns]
sample_sd <- apply(X = simulations, MARGIN = 2, FUN=sd)
sample_means
sample_sd
```

```{r}
#histogram of sample means [for mu hat mm]
hist(sample_means)
```

```{r}
#statistics for mu mm such as mean and standard error
mu_sample_mean <- mean(sample_means)
se_sample_mean <- sqrt(var(sample_means))
mu_sample_mean
se_sample_mean #this is se(mu hat mm)
```

```{r}
#histogram of sample sd's [for sigma hat mm]
hist(sample_sd)
```
```{r}
mu_sample_sd <- mean(sample_sd)
se_sample_sd <- sqrt(var(sample_sd))
mu_sample_sd
se_sample_sd
```
```{r}
sample_means <- data.frame(sample_means)
sample_sd <- data.frame(sample_sd)
```

```{r}
#(3) (c)
#true values of mu and sigma are 2 and 2. Re-plotting histograms with true values
library(ggplot2)
mu_hist <- ggplot(sample_means, aes(x=sample_means)) + geom_histogram() + geom_vline(aes(xintercept = 2))
sd_hist <- ggplot(sample_sd, aes(x=sample_sd)) + geom_histogram() + geom_vline(aes(xintercept = 2))
```

```{r}
mu_hist
```

```{r}
sd_hist
```

