---
title: "stat135_hw6"
author: "Vinay Maruri"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#problem 4#
```{r}
pf(21.47/2.39, 3, 17, lower.tail=FALSE)
```

#problem 5#
```{r}
low = c(3.89, 3.87, 3.26, 2.70, 3.82, 3.23)
med = c(8.54, 9.32, 8.76, 9.30, 10.45, 8.94, 10.37)
high = c(20.39, 24.22, 39.91, 22.78, 26.33)
```

```{r}
obs = list(low, med, high)
k = length(obs)
n = length(unlist(obs))
```

```{r}
k-1
n-k
n-1
```


```{r}
#squares within groups
S_W = lapply(obs, function(vec) sum((vec = mean(vec))^2))
print(unlist(S_W))
sum(unlist(S_W))
```

```{r}
#squares between groups
tot_mean = mean(unlist(obs))
S_B = lapply(obs, function(vec) length(vec)*(mean(vec) - tot_mean)^2)
print(unlist(S_B))
sum(unlist(S_B))
```

```{r}
#f-stat, mean-squares
sum(unlist(S_B))/(k-1)
sum(unlist(S_W))/(n-k)
{sum(unlist(S_B))/(k-1)}/{sum(unlist(S_W))/(n-k)}
```

```{r}
#critical value
qf(0.95, k-1, n-k, lower.tail=FALSE)
```

```{r}
#p-value
pf(14.44844, k-1, n-k, lower.tail=FALSE)
```

```{r}
#bonferroni intervals, using code from lab 11.
get_bound <- function(vec, lower){ #By default returns the lower bound
  center = mean(vec)
  n = length(vec)
  halfwidth = qt(1 - 0.025/3, df = n - 1)*sd(vec)/sqrt(n)
  if(lower == T) {
    return(center - halfwidth)
  }
  else{
    return(center + halfwidth)
  }
}
upperbounds <- sapply(obs, get_bound, lower = F)
lowerbounds <- sapply(obs, get_bound, lower = T)
upperbounds
lowerbounds
```

#problem 6#
```{r}
toxin1 = c(28, 23, 14, 27)
toxin2 = c(33, 36, 34, 29, 31, 34)
toxin3 = c(18, 21, 20, 22, 24)
control = c(11, 14, 11, 16)
obs2 = list(toxin1, toxin2, toxin3, control)
```

```{r}
get_pair_diff_CI <- function(pair, Observations, alpha=0.05, m1, m2){
  vec1 = m1*Observations[[pair[1]]]
  vec2 = m2*Observations[[pair[2]]]
  center1 = mean(vec1)
  center2 = mean(vec2)
  n1 = length(vec1)
  n2 = length(vec2)
  k = length(Observations)
  m = k*(k-1)/2
  Sp2 = {(n1 - 1)*var(vec1) + (n2 - 1)*var(vec2)}/(n1+n2-2)
  halfwidth = qt(1 - (alpha/2)/m, df=n1+n2-2)*sqrt(Sp2*(1/n1 + 1/n2))
  return(c(center1 - center2, center1-center2-halfwidth, center1-center2+halfwidth))
}
#bonferroni CI for 3 pairwise differences.
get_trip_diff_CI <- function(pair, Observations, alpha=0.05, m1, m2, m3){
  vec1 = m1*Observations[[pair[1]]]
  vec2 = m2*Observations[[pair[2]]]
  vec3 = m3*Observations[[pair[3]]]
  center1 = mean(vec1)
  center2 = mean(vec2)
  center3 = mean(vec3)
  n1 = length(vec1)
  n2 = length(vec2)
  n3 = length(vec3)
  k = length(Observations)
  m = k*(k-1)/2
  Sp2 = {(n1 - 1)*var(vec1) + (n2 - 1)*var(vec2) + (n3 - 1)*var(vec3)}/(n1+n2+n3-3)
  halfwidth = qt(1 - (alpha/3)/m, df=n1+n2+n3-3)*sqrt(Sp2*(1/n1 + 1/n2 + 1/n3))
  return(c(center1 - center2 - center3, center1-center2-center3-halfwidth, center1-center2-center3+halfwidth))
}
```

```{r}
get_pair_diff_CI(c(1, 2), obs2, m1=1, m2=1)
```

```{r}
get_trip_diff_CI(c(1, 2, 4), obs2, m1=1, m2=2, m3=-1)
```
```{r}
get_trip_diff_CI(c(3, 1, 2), obs2, m1=3, m2=1, m3=2)
```

```{r}
get_trip_diff_CI(c(2, 3, 4), obs2, m1=5, m2=4, m3=1)
```

```{r}
get_trip_diff_CI(c(2, 1, 3), obs2, m1=2, m2=1, m3=1)
```

```{r}
#scheffe confidence intervals.
get_pair_diff_CI_2 <- function(pair, Observations, alpha=0.05, m1, m2){
  vec1 = m1*Observations[[pair[1]]]
  vec2 = m2*Observations[[pair[2]]]
  center1 = mean(vec1)
  center2 = mean(vec2)
  n1 = length(vec1)
  n2 = length(vec2)
  k = length(Observations)
  m = k*(k-1)/2
  Sp2 = {(n1 - 1)*var(vec1) + (n2 - 1)*var(vec2)}/(n1+n2-2)
  c = qf(0.95, k-1, (n1+n2)-k, lower.tail=FALSE)
  halfwidth = qt(c, df=n1+n2-2)*sqrt(Sp2*(1/n1 + 1/n2))
  return(c(center1 - center2, center1-center2-halfwidth, center1-center2+halfwidth))
}
get_trip_diff_CI_2 <- function(pair, Observations, alpha=0.05, m1, m2, m3){
  vec1 = m1*Observations[[pair[1]]]
  vec2 = m2*Observations[[pair[2]]]
  vec3 = m3*Observations[[pair[3]]]
  center1 = mean(vec1)
  center2 = mean(vec2)
  center3 = mean(vec3)
  n1 = length(vec1)
  n2 = length(vec2)
  n3 = length(vec3)
  k = length(Observations)
  m = k*(k-1)/2
  Sp2 = {(n1 - 1)*var(vec1) + (n2 - 1)*var(vec2) + (n3 - 1)*var(vec3)}/(n1+n2+n3-3)
  c = qf(0.95, k-1, (n1+n2+n3)-k, lower.tail=FALSE)
  halfwidth = qt(c, df=n1+n2+n3-3)*sqrt(Sp2*(1/n1 + 1/n2 + 1/n3))
  return(c(center1 - center2 - center3, center1-center2-center3-halfwidth, center1-center2-center3+halfwidth))
}
```

```{r}
get_pair_diff_CI_2(c(1, 2), obs2, m1=1, m2=1)
```

```{r}
get_trip_diff_CI_2(c(1, 2, 4), obs2, m1=1, m2=2, m3=-1)
```

```{r}
get_trip_diff_CI_2(c(3, 1, 2), obs2, m1=3, m2=1, m3=2)
```

```{r}
get_trip_diff_CI_2(c(2, 3, 4), obs2, m1=5, m2=4, m3=1)
```

```{r}
get_trip_diff_CI_2(c(2, 1, 3), obs2, m1=2, m2=1, m3=1)
```

#problem7#

```{r}
tablet_data = read.delim2("C:/Users/EndlessWormhole/Desktop/stat_135/tablets_lab11.txt", header = TRUE, sep = "\t", dec = ".")
```

```{r}
names <- rep(colnames(tablet_data), each=10)
special_tukey_data = data.frame(Obs = c(tablet_data$X.Lab1., tablet_data$X.Lab2., tablet_data$X.Lab3., tablet_data$X.Lab4., tablet_data$X.Lab5., tablet_data$X.Lab6., tablet_data$X.Lab7.), ind = names)
```

```{r}
get_pair_diff_CI(c(2, 1), tablet_data, m1=1, m2=1)
get_pair_diff_CI_2(c(2, 1), tablet_data, m1=1, m2=1)
```
```{r}
anova_fit <- aov(Obs ~ ind, data = special_tukey_data)
summary(anova_fit)
```

```{r}
TukeyHSD(x=anova_fit, which = 'ind', conf.level = 0.95)
```

```{r}
get_pair_diff_CI(c(3, 1), tablet_data, m1=1, m2=1)
get_pair_diff_CI_2(c(3, 1), tablet_data, m1=1, m2=1)
```

```{r}
get_pair_diff_CI(c(3, 2), tablet_data, m1=1, m2=1)
get_pair_diff_CI_2(c(3, 2), tablet_data, m1=1, m2=1)
```

#problem 8#

```{r}
p = 6
cell_names = expand.grid(species = c('a', 'b', 'c'), fertilizers = c('Control', 'F1', 'F2', 'F3'))
repeats = rep(1:nrow(cell_names), each=p)
Cell_names = cell_names[repeats, ]
obs = c(21.0, 32.0, 22.5, 28.0, 19.5, 30.5, 26.0, 27.5,
22.5, 25.0, 28.0, 31.0,
21.5, 27.5, 27.0, 29.5,
20.5, 28.0, 26.5, 30.0,
21.0, 28.6, 25.2, 29.2,
23.7, 30.1, 30.6, 36.1,
23.8, 28.9, 31.1, 36.6,
23.7, 34.4, 34.9, 37.1,
22.8, 32.7, 30.1, 36.8,
22.8, 32.7 ,30.1 ,36.8,
24.4, 32.7 ,25.5 ,37.1,
25.1, 28.4 ,22.8 ,32.8,
22.6, 26.4 ,23.2 ,34.3,
24.5, 27.8 ,26.4 ,33.3,
23.7, 26.7 ,23.8 ,31.9,
22.6, 25.3, 25.4, 32.6,
23.9, 25.9, 22.7, 30.6)
obs_w_names = data.frame(species = factor(Cell_names$species), ferts = factor(Cell_names$fertilizers), Obs=obs)
```


```{r}
#creating treatment means plot.
Cell_means <- aggregate(Obs ~ species + ferts, data = obs_w_names, FUN = mean)  

library(ggplot2)
ggplot(data=Cell_means,  
    aes(x=species, y=Obs, group=ferts, color=ferts)) +
  geom_line(size = 0.8) + geom_point() + ylab("Cell means")
```

#start calculating two-way anova stats.#

```{r}
#bookkeeping
I = 3; J = 4; n=nrow(obs_w_names)
all_mean = mean(obs_w_names$Obs)
#SS_A
S_A = aggregate(Obs~species, data = obs_w_names, FUN = function(vec) length(vec)*(mean(vec)-all_mean)^2)
S_A
```

```{r}
SS_A = sum(S_A$Obs)
SS_A
```


```{r}
#SS_B
S_B = aggregate(Obs~ferts, data = obs_w_names, FUN = function(vec) length(vec)*(mean(vec)-all_mean)^2)
S_B
```

```{r}
SS_B = sum(S_B$Obs)
SS_B
```


```{r}
#SS_E
S_E = aggregate(Obs~species+ferts, data = obs_w_names, FUN = function(vec) sum((vec-mean(vec))^2))
head(S_E, 6)
```

```{r}
SS_E = sum(S_E$Obs)
SS_E
```


```{r}
#SS_AB
cell_mean = aggregate(Obs~species+ferts, data = obs_w_names, FUN = mean)
cell_mean_vec = rep(cell_mean$Obs, each=p)
A_means = aggregate(Obs~species, data = obs_w_names, FUN = mean)
A_means_vec = rep(rep(A_means$Obs, times = J), each = p)
B_means = aggregate(Obs~ferts, data = obs_w_names, FUN = mean)
B_means_vec = rep(rep(B_means$Obs, each = I), each = p)
Tmp_data = cbind(cell_mean_vec, A_means_vec, B_means_vec, all_mean)
S_AB = apply(Tmp_data, 1, function(vec) (vec[1]-vec[2]-vec[3]+vec[4])^2)
SS_AB = sum(S_AB)
SS_AB
```

```{r}
#main effect of A
F_stat = {SS_A/(I-1)}/{SS_E/(n-I*J)}
F_stat
qf(0.05, I-1, n-I*J, lower.tail=FALSE)
pf(F_stat, I-1, n-I*J, lower.tail = FALSE)
```


```{r}
#main effect of B
F_stat = {SS_B/(J-1)}/{SS_E/(n-I*J)}
F_stat
qf(0.05, J-1, n-I*J, lower.tail=FALSE)
pf(F_stat, J-1, n-I*J, lower.tail = FALSE)
```

```{r}
#main effect of A*B
F_stat = {SS_AB/((I-1)*(J-1))}/{SS_E/(n-I*J)}
F_stat
qf(0.05, (I-1)*(J-1), n-I*J, lower.tail=FALSE)
pf(F_stat, (I-1)*(J-1), n-I*J, lower.tail = FALSE)
```




```{r}
#test my results against anova() as specified in question.
fit = lm(Obs ~ species*ferts, data = obs_w_names)
anova(fit)
```

#problem 10#

```{r}
pottery_data = read.delim2("C:/Users/EndlessWormhole/Desktop/stat_135/pottery.txt", header = TRUE, sep = " ", dec = ".")
pottery_data = pottery_data[, 1:6]
colnames(pottery_data) <- c("sites", "Al", "Fe", "Mg", "Ca", "Na")
```


```{r}
#MANOVA
pottery_man = manova(cbind(Al, Fe, Mg, Ca, Na) ~ sites, data = pottery_data)
summary(pottery_man)
```

```{r}
summary(pottery_man, 'Wilks')
```


```{r}
summary(pottery_man, 'Hotelling-Lawley')
```

```{r}
summary(pottery_man, 'Roy')
```





